"""
This code plug in the first-stage optimized variables in both SDDP and two-stage model by the 
train set of data to a SDDP model with constraint generated by the test set of the data, 
and compare their performance.
"""

using SDDP, HiGHS
using DataFrames, CSV
using Distributions
using LinearAlgebra

include("read_data_sddp.jl")
include("read_first_stage_sddp.jl")

T = 24
#const scaling_factor = 1e-3

# Read the average values from previous simulation
first_stage_sddp = read_first_stage_sddp("output/simulations/sddp_train/")

model1 = SDDP.MarkovianPolicyGraph(
    transition_matrices = transition_matrix,
    sense = :Min,
    lower_bound = 0.0,
    optimizer = HiGHS.Optimizer
) do subproblem, node
    # Unpack the stage and Markov index
    t, markov_state = node
    
    # State variables
    @variable(subproblem, 0 <= stored[i=1:4] <= hydro_.UB[i], SDDP.State, 
                initial_value = stored_initial[i])
        
    # Control variables
    @variable(subproblem, 0 <= spill[i=1:4])
    @variable(subproblem, 0 <= hydro[i=1:4] <= hydro_.UB[i+8])
    @variable(subproblem, 0 <= deficit[r=1:4, d=1:4] <= demand[t%12 == 0 ? 12 : t%12, r] * deficit_.DEPTH[d])
    
    # Exchange variables - create with bounds separately
    @variable(subproblem, 0 <= exchange[i=1:5,j=1:5] <= exchange_ub[i,j])
    
    # Thermal variables
    @variable(subproblem, thermal_gen[p=1:4,u=1:size(thermal[p],1)], 
        lower_bound = thermal[p].LB[u],
        upper_bound = thermal[p].UB[u])
    
    # Random variables
    @variable(subproblem, inflow[1:4])

    # Get unique scenarios from current state's Markov matrix
    noise_terms = collect(eachrow(Markov_states[t]))

    # Parameterize the model
    SDDP.parameterize(subproblem, noise_terms) do ω
        for j in 1:4
            JuMP.fix(inflow[j], ω[j])
        end
    end

    # Objective function
    @stageobjective(subproblem,
        0.001 * sum(spill) +
        sum(deficit_.OBJ[d] * deficit[r,d] for r in 1:4, d in 1:4) +
        sum(exchange_cost[i,j] * exchange[i,j] for i in 1:5, j in 1:5) +
        sum(thermal[p].OBJ[u] * thermal_gen[p,u] for p in 1:4, u in 1:size(thermal[p],1))
    )

    # Constraints
    # Water balance
    @constraint(subproblem, [i=1:4], 
                stored[i].out == stored[i].in - hydro[i] - spill[i] + inflow[i])

    # Power balance
    @constraint(subproblem, [r=1:4],
        sum(thermal_gen[r,u] for u in 1:size(thermal[r],1)) +
        sum(deficit[r,d] for d in 1:4) +
        hydro[r] -
        sum(exchange[r,j] for j in 1:5) +
        sum(exchange[j,r] for j in 1:5) ==
        demand[t%12 == 0 ? 12 : t%12, r])

    # Exchange balance
    @constraint(subproblem,
        sum(exchange[j,5] for j in 1:5) -
        sum(exchange[5,j] for j in 1:5) == 0)

    # Initial conditions
    if t == 1
        @constraint(subproblem, [i=1:4], stored[i].in == stored_initial[i])
        @constraint(subproblem, [i=1:4], inflow[i] == inflow_initial[i])
        @constraint(subproblem, [i=1:4], stored[i].out == first_stage_sddp[:stored][i])
        @constraint(subproblem, [i=1:4], spill[i] == first_stage_sddp[:spill][i])
        @constraint(subproblem, [i=1:4], hydro[i] == first_stage_sddp[:hydro][i])
        @constraint(subproblem, [r=1:4, d=1:4], deficit[r,d] == first_stage_sddp[:deficit][r,d])
        @constraint(subproblem, [i=1:5, j=1:5], exchange[i,j] == first_stage_sddp[:exchange][i,j])
        @constraint(subproblem, [p=1:4, u=1:size(thermal[p],1)], 
            thermal_gen[p,u] == first_stage_sddp[:thermal_gen][p][u])
    end
end

SDDP.train(model1, 
    iteration_limit=40,
    print_level=1,
    log_frequency=1,
    stopping_rules = [
        SDDP.BoundStalling(5, 1e-4)  # Stop if bound doesn't improve by 1e-4 in 5 iterations
    ],
    risk_measure = SDDP.Expectation(),
    #dashboard = true
)

# Simulate policy
simulations1 = SDDP.simulate(model1, 100)

